#!/bin/sh
set -e

PRIMARY_CONFIG_PATH="${ESPERTA_CODE_CONFIG_PATH:-/home/feliz/.esperta-code/esperta-code.yml}"
LEGACY_CONFIG_PATH="${FELIZ_CONFIG_PATH:-/home/feliz/.feliz/feliz.yml}"
CONFIG_PATH="$PRIMARY_CONFIG_PATH"
if [ ! -f "$CONFIG_PATH" ] && [ -f "$LEGACY_CONFIG_PATH" ]; then
  CONFIG_PATH="$LEGACY_CONFIG_PATH"
fi

# --- Preflight checks ---
echo "Esperta Code preflight checks..."

check_tool() {
  if command -v "$1" >/dev/null 2>&1; then
    echo "  [OK] $1 found: $($1 --version 2>&1 | head -1)"
  else
    echo "  [WARN] $1 not found"
  fi
}

check_tool bun
check_tool git
check_tool gh

# Check agent CLIs
AGENT_FOUND=0
if command -v claude >/dev/null 2>&1; then
  echo "  [OK] claude found"
  AGENT_FOUND=1
fi
if command -v codex >/dev/null 2>&1; then
  echo "  [OK] codex found"
  AGENT_FOUND=1
fi
if [ "$AGENT_FOUND" -eq 0 ]; then
  echo "  [WARN] No agent CLI found. Install one:"
  echo "         claude: curl -fsSL https://claude.ai/install.sh | bash"
  echo "         codex:  npm install -g @openai/codex"
fi

# Check GitHub CLI auth
if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then
    echo "  [OK] gh authenticated"
  else
    if [ -n "$GITHUB_TOKEN" ] || [ -n "$GH_TOKEN" ]; then
      echo "  [OK] gh will authenticate via GITHUB_TOKEN/GH_TOKEN env var"
    else
      echo "  [WARN] gh not authenticated. Set GITHUB_TOKEN or run 'gh auth login'."
    fi
  fi
fi

# Check required env vars
if [ -z "$LINEAR_OAUTH_TOKEN" ]; then
  echo "  [WARN] LINEAR_OAUTH_TOKEN not set. Linear integration will stay disabled until configured."
fi
if [ -z "$GITHUB_TOKEN" ] && [ -z "$GH_TOKEN" ]; then
  echo "  [WARN] GITHUB_TOKEN not set. GitHub operations (PR creation) will fail."
  echo "         Create a token with 'repo' scope at https://github.com/settings/tokens"
fi

echo ""

# --- Auto-generate config if none exists ---
if [ ! -f "$CONFIG_PATH" ]; then
  echo "No config found at $CONFIG_PATH. Generating from environment..."
  mkdir -p "$(dirname "$CONFIG_PATH")"

  if [ -n "$LINEAR_OAUTH_TOKEN" ]; then
    LINEAR_CONFIG=$(cat <<'YAML'
linear:
  oauth_token: $LINEAR_OAUTH_TOKEN

YAML
)
  else
    LINEAR_CONFIG=$(cat <<'YAML'
# Optional: enable the Linear connector later
# linear:
#   oauth_token: $LINEAR_OAUTH_TOKEN

YAML
)
  fi

  cat > "$CONFIG_PATH" <<YAML
# Auto-generated by docker-entrypoint.sh
$LINEAR_CONFIG

runtime:
  data_dir: /data/esperta-code
  max_concurrent_jobs: 4

webhook:
  port: 3421

storage:
  data_dir: /data/esperta-code
  workspace_root: /data/esperta-code/workspaces

agent:
  default: claude-code

projects: []
YAML
  echo "Config written to $CONFIG_PATH"
  echo ""
  echo "Next steps:"
  echo "  1. Install an agent: docker compose exec esperta-code bash"
  echo "     claude: curl -fsSL https://claude.ai/install.sh | bash"
  echo "     codex:  npm install -g @openai/codex"
  echo "  2. If using Linear:  docker compose exec esperta-code bun run src/cli/index.ts auth linear"
  echo "  3. Add a project:    docker compose exec esperta-code bun run src/cli/index.ts project add"
  echo ""
fi

# --- Validate config ---
echo "Validating configuration..."
if bun run src/cli/index.ts config validate --config "$CONFIG_PATH"; then
  echo ""
else
  echo ""
  echo "[WARN] Config validation failed. The daemon will start but may encounter errors."
  echo ""
fi

# --- Run the command ---
exec bun run src/cli/index.ts --config "$CONFIG_PATH" "$@"
